### ISSUE TITLE
Define the app stack

### ISSUE THREAD

**Issue by margintop15px** [moscow-clojure-meetup/dojos#5]
DB - Datahike https://github.com/replikativ/datahike
State management - Duct https://github.com/duct-framework/duct
API Layer - GraphQL (Lacinia) https://github.com/walmartlabs/lacinia

**To be discussed:**
- **Server**: 
  Pedestal http://pedestal.io/index
  http-kit https://github.com/http-kit/http-kit + reitit https://github.com/metosin/reitit
  Not sure that Pedestal can work with a WebSockets but http-kit definitely does (probably it's not so critical if we'll have the graphql subscriptions)

- **Frontend**: 
  RUM https://github.com/tonsky/rum
  helix https://github.com/lilactown/helix
  Reframe https://github.com/Day8/re-frame
  keechma/next https://github.com/keechma/keechma-next
  Fulcro https://fulcro.fulcrologic.com/
  I'd like to keep the frontend as simple as possible. All business logic ideally should live on the backend side and only a representation logic should be in the frontend. Also, I think the use of React and its whole ecosystem will speed up the development

**Comment by skammer** [comment]
I vote for http-kit + reitit and reframe as it's probably the most battle tested combination

**Comment by margintop15px** [comment]
@skammer what do you think about the https://github.com/roman01la/uix ?

**Comment by margintop15px** [comment]
OK. Stack used for now:
- Duct / integrant
- Datahike
- http-kit
- reitit
- lacinia
- reagent
- re-graph

Things to decide:
- UI framework (material UI, semantic UI, Bulma, bootstrap, etc.)
- Apollo Client instead of re-graph
- Where to deploy

@esseswann @skammer @AlexeyPopov 
any thoughts?
